# ~ 301.59 MB
FROM ruby:2.6.10

# ~ 23.67 MB
# FROM ruby:2.6.10-alpine

# It did not work unfortunately, did not source ~/.bashrc. Default shell here is "/bin/sh" so far.
# Set bash as a default shell (double quote is must here).
# Once the default shell is bash, the \. ~/.bashrc will be run when new shell is opened.
# Check ~/.profile for clarification.
# SHELL ["/bin/bash", "-c"]

WORKDIR '/sidekiq'

COPY ./Gemfile ./

COPY ./Gemfile.lock ./

RUN bundle install

# Install cron daemon to execute scheduled commands
RUN apt-get update && apt-get install -y cron

# Install nvm (node version manager)
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

# Install node js, newer version is having problems with webpacker.
RUN . ~/.bashrc && nvm install 14.0.0

# Needed by npm.
RUN apt-get update && apt-get -y install python2

COPY ./package.json ./

COPY ./package-lock.json ./

# Install node js packages, you may need VPN as some sources are not available from certain locations.
RUN . ~/.bashrc && npm install

# Solve - yarn: command not found error.
RUN . ~/.bashrc && npm install --global yarn

COPY ./yarn.lock ./

# Install all the javascript packages with yarn.
RUN . ~/.bashrc && yarn install --check-files
