default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL_ACTION_CABLE") { "redis://localhost:6379/1" } %>


development:
  <<: *default
  channel_prefix: events_development

test:
  adapter: events_test

production:
  <<: *default
  channel_prefix: events_production
